### ISSUE TITLE
Output shape

### ISSUE THREAD

**Issue by krishnak** [zhen8838/keras-yolo3#5]
@zhen8838 

In this [code](https://github.com/zhen8838/K210-yolo3/blob/2c498616208dd85c48d3b70ccab6680b6cc2739b/kpu_yolov3_test/main.c#L312)

What is the shape of output 0 and 1 which comes from KPU

**Comment by zhen8838** [comment]
c array. len=C x H x W

**Comment by krishnak** [comment]
I mean is that a single dimension array? or can it be a 3 dimensional array?

For ex: Keras output is 3x7x10 is this have to be reshaped to 1x210 in KPU or can the KPU also output 3x7x10

**Comment by krishnak** [comment]
I think the confusion arose from the difference between your [code](https://github.com/zhen8838/K210_Yolo_framework/blob/e5350c0166e1c9d9acb63166c31a17c514b31f04/yolo3_frame_test_public/main.c#L282)


where the output is of shape 10x7x75

however in [Kendryte](https://github.com/kendryte/nncase/blob/4082826f0f0d706c500debf62ddad9c0b174f547/examples/20classes_yolo/k210/kpu_20classes_example/main.c#L243) repository this is  mentioned as 10x7x125

You are using V3 anchors, Kendryte is using V2 anchors

**Comment by zhen8838** [comment]
- c array is one dimension.

- anchors num is different

  10x7x75 => w=10 ,h=7, anchor=3 x (class=20 + obj=1 + coord=4)=75

  Kendryte repository use one dectect layer, his anchor=5. I use 2 detect layers, each layer have 3 anchors.

**Comment by krishnak** [comment]
yes got it thanks
